### ISSUE TITLE
Microsoft 365 suite Service not listed by script

### ISSUE THREAD

**Issue by marosonda** [einast/PS_M365_scripts#3]
Hi,

I tried to implement your script in our test tenant and it works nice with one little problem. Yesterday there was incident on O365 service named " Microsoft 365 suite ". And this service is not covered by your script. Other 2 incidents, which were on Sharepoint and Teams are added as a message card to my channel but this one is missing. Is there any additional variable for this service which needs to be added to the script ?

**Comment by einast** [comment]
Hi, thanks for the notification. I'm sitting at a customer with limited testing possibilities, but I added the Microsoft 365 Suite service in the scripts now.

**Comment by marosonda** [comment]
Thanks, it works.
