### ISSUE TITLE
Invoke-RestMethod throwing forbidden error 403 

### ISSUE THREAD

**Issue by FlyingCowInTheAir** [einast/PS_M365_scripts#8]
We are getting Invoke-RestMethod throwing forbidden error 403, any suggestions ?

**Comment by einast** [comment]
Hi, 403 points to a permission issue. Can you check that everything is set up correctly, and then run the script again? I'm not sure where you run the script from, but I mainly use Azure Automation. If that's the case, some pointers are found here: https://docs.microsoft.com/en-us/answers/questions/881179/403-error-in-invoke-webrequest-azure-automation-ac.html (Invoke-WebRequest, but the troubleshooting steps outlined a bit down on the page are the same).

**Comment by FlyingCowInTheAir** [comment]
Hi! Thanks for your quick reply !
I run the script local and in Azure Automation with the same result, and I registrated the app as discribed in the link.
Not much room for errors :) I look at the link you posted. Thanks.

**Comment by FlyingCowInTheAir** [comment]
it seems that you need ServiceHealth.Read.All and ServiceMessage.Read.All as well on the API acces

**Comment by einast** [comment]
Great, probably some changes since I originally wrote the script and blog posts. I haven't really used the scripts in a while, as my customer assignments have been focusing on other areas. I will try to get some time to update the posts to reflect the permission changes. Thanks!
